num_requests: 2
start_date: "20201201"
end_date: "20220901"
freq: "MS" # pandas attribite
output_folder: "results/cacheb/"

# CACHEB cacheb.dcms.destine.eu
cacheb_url: https://cacheb.dcms.destine.eu/destine-climate-dt/SSP3-7.0-IFS-NEMO-0001-standard-sfc-v0.zarr
capital_coordinates: {
    # "Vienna": [48.2082, 16.3738],
    "Brussels": [50.8503, 4.3517],
    # "Sofia": [42.6977, 23.3219],
    # "Zagreb": [45.8150, 15.9819],
    # "Nicosia": [35.1856, 33.3823],
    # "Prague": [50.0755, 14.4378],
    # "Copenhagen": [55.6761, 12.5683],
    # "Tallinn": [59.4370, 24.7535],
    # "Helsinki": [60.1695, 24.9355],
    "Paris": [48.8566, 2.3522],
    # "Berlin": [52.5200, 13.4050],
    # "Athens": [37.9838, 23.7275],
    # "Budapest": [47.4979, 19.0402],
    # "Dublin": [53.3498, -6.2603],
    "Rome": [41.9028, 12.4964],
    # "Riga": [56.9496, 24.1052],
    # "Vilnius": [54.6872, 25.2797],
    # "Luxembourg": [49.6117, 6.1319],
    # "Valletta": [35.8970, 14.5126],
    # "Amsterdam": [52.3676, 4.9041],
    # "Warsaw": [52.2297, 21.0122],
    # "Lisbon": [38.7223, -9.1393],
    # "Bucharest": [44.4268, 26.1025],
    # "Bratislava": [48.1486, 17.1077],
    # "Ljubljana": [46.0569, 14.5058],
    # "Madrid": [40.4168, -3.7038],
    # "Stockholm": [59.3293, 18.0686]
    }

# POLYTOPE
polytope_request:
  activity: ScenarioMIP
  class: d1
  dataset: climate-dt
  date: "20201201"
  experiment: SSP3-7.0
  expver: 0001
  generation: 1
  levtype: sfc
  model: IFS-NEMO
  param: 167
  realization: 1
  resolution: standard
  stream: clte
  # time: '00/01/02'

  time: '00/01/02'
  type: fc

polytope_url: polytope.lumi.apps.dte.destination-earth.eu
grid:
  lat: 0.3
  lon: 0.3
  method: linear
